# updated dvc.yaml

stages:
  data_ingestion:
    cmd: python src/data/make_dataset.py
    deps:
    - src/data/make_dataset.py
    params:
    - data_ingestion.test_size
    outs:
    - data/raw

  data_preprocessing:
    cmd: python src/data/preprocess.py
    deps:
    - data/raw
    - src/data/preprocess.py
    outs:
    - data/interim

  feature_engineering:
    cmd: python src/features/build_features.py
    deps:
    - data/interim
    - src/features/build_features.py
    params:
    - feature_engineering.max_features
    outs:
    - data/processed
    - models/vectorizer.pkl

  model_building:
    cmd: python src/model/train_model.py
    deps:
    - data/processed
    - src/model/train_model.py
    outs:
    - models/model.pkl

  model_evaluation:
    cmd: python src/model/predict_model.py
    deps:
    - models/model.pkl
    - src/model/predict_model.py
    metrics:
    - reports/metrics.json
    outs:
    - reports/experiment_info.json  # Add the model_info.json file as an output
  
  model_registration:
    cmd: python src/model/register_model.py
    deps:
    - reports/experiment_info.json
    - src/model/register_model.py