name: CI Pipeline

on: push 

jobs: 
  project-testing:
    runs-on: ubuntu-latest

    steps: 
      - name: code checkout
        uses: actions/checkout@v3 

      - name: setup python
        uses: actions/setup-python@v2
        with: 
          python-version: '3.14'
          
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: install dependencies
        run: |
          pip install -r requirements.txt 

      - name: run pipeline 
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          dvc repro 


      - name: Run model tests
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: |
          python -m unittest tests/test_model.py
      

      - name: Promote model to production
        if: success()   # this line means that this step will only execute if all the previous steps ran successfully
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python scripts/promote_model.py


      - name: Run Flask app tests
        if: success()
        env:
          DAGSHUB_PAT: ${{ secrets.DAGSHUB_PAT }}
        run: python -m unittest tests/test_flask_app.py
      
      - name: Login to AWS ECR
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin 825765400473.dkr.ecr.ap-southeast-2.amazonaws.com


      - name: Build Docker Image 
        run: |
          docker build -t krishna_ecr .

      - name: Tag Docker Image
        run: |
          docker tag krishna_ecr:latest 825765400473.dkr.ecr.ap-southeast-2.amazonaws.com/krishna_ecr:latest

      - name: Push Docker Image to AWS ECR
        run: |
          docker push 825765400473.dkr.ecr.ap-southeast-2.amazonaws.com/krishna_ecr:latest 